package org.radargun;

import org.radargun.state.MainState;

/**
 * A main stage is a stage that only gets executed on the main. E.g. report generation is suitable for being a
 * main stage, as it is only the main having access to all the reports generated by the nodes.
 *
 * @author Mircea Markus &lt;Mircea.Markus@jboss.com&gt;
 */
public interface MainStage extends Stage {

   void init(MainState mainState);

   StageResult execute() throws Exception;
}
